#define PJMEDIA_CONF_USE_SWITCH_BOARD 	   1
#define PJMEDIA_CONF_SWITCH_BOARD_BUF_SIZE 2000

#define PJSUA_MAX_CALLS 	128
#define PJSUA_MAX_PLAYERS 	256
#define PJ_IOQUEUE_MAX_HANDLES 	256

#define PJMEDIA_CODEC_L16_HAS_48KHZ_MONO 1