name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [bionic, centos7]
    container: infactum/tg2sip-builder:${{ matrix.tag }}
      
    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: |
        [ -d "/opt/rh" ] && source /opt/rh/devtoolset-7/enable
        mkdir build && cd build
        export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . -j $(grep -c ^processor /proc/cpuinfo);
        
    - uses: actions/upload-artifact@v2
      with:
        name: tg2sip_${{ matrix.tag }}
        path: |
          tg2sip
          gen_db
          settings.ini
    
